In [1]:
import pandas as pd
import numpy as np
import pickle

In [2]:
from sklearn.datasets import load_iris

In [3]:
iris=load_iris()

In [4]:
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [5]:
df=pd.DataFrame(iris.data,columns=iris.feature_names)

In [6]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [7]:
df['target']=iris.target

In [8]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [9]:
df.isnull().sum()

sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
target               0
dtype: int64

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
X_train, X_test, y_train, y_test=train_test_split(df.drop(['target'],axis=1),df.target,train_size=0.9)


In [34]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.cluster import KMeans
from sklearn.linear_model import LogisticRegression

In [13]:
from sklearn.model_selection import cross_val_score

In [14]:
cross_val_score(RandomForestClassifier(),X_train,y_train,cv=5)

array([0.92592593, 0.92592593, 0.96296296, 1.        , 0.96296296])

In [15]:
cross_val_score(KMeans(n_clusters=3),X_train,y_train,cv=5)

C:\Users\Divyanshu\anaconda3\lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
C:\Users\Divyanshu\anaconda3\lib\site-packages\sklearn\cluster\_kmeans.py:1382: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(
C:\Users\Divyanshu\anaconda3\lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
C:\Users\Divyanshu\anaconda3\lib\site-packages\sklearn\cluster\_kmeans.py:1382: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setti

array([-12.98087401, -14.61572053, -16.27752088, -11.67839022,
       -17.92419101])

In [35]:
cross_val_score(LogisticRegression(),X_train,y_train)

C:\Users\Divyanshu\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Divyanshu\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
 

array([0.96296296, 0.92592593, 0.96296296, 1.        , 0.96296296])

# test data set

In [17]:
cross_val_score(RandomForestClassifier(),X_test,y_test,cv=5)

C:\Users\Divyanshu\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:700: UserWarning: The least populated class in y has only 3 members, which is less than n_splits=5.
  warnings.warn(


array([1.        , 1.        , 0.66666667, 1.        , 1.        ])

In [45]:
reg=RandomForestClassifier()

In [46]:
reg.fit(X_train,y_train)

RandomForestClassifier()

In [47]:
reg.predict([[5.1,3.5,1.4,0.2]])

C:\Users\Divyanshu\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([0])

In [48]:
reg.score(X_test,y_test)

1.0

In [49]:
targets = iris.target_names

In [52]:
reg.predict(X_test)

array([2, 0, 2, 1, 2, 0, 1, 1, 0, 0, 2, 2, 2, 0, 0])

In [53]:
format(targets[reg.predict(X_test)])

"['virginica' 'setosa' 'virginica' 'versicolor' 'virginica' 'setosa'\n 'versicolor' 'versicolor' 'setosa' 'setosa' 'virginica' 'virginica'\n 'virginica' 'setosa' 'setosa']"

In [51]:
with open("iris.pickle",'wb') as f:
    pickle.dump(reg,f)